#!/usr/bin/env bash
#A Bash script that configures a new Ubuntu machine to
#Install nginx on your web-01 server while listening on
#port 80, querying Nginx at its root / with a GET 
#request (requesting a page) using curl, and return a
#page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
